services:
  # Service
  tasks_fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: fastapi_dev
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      - ENVIRONMENT=test
      - DB_URL=postgresql+asyncpg://user:password@postgres:5432/tasks
      - CACHE_TTL=5
      - KEYCLOAK_CLIENT_ID=tasks
      - KEYCLOAK_CLIENT_SECRET_KEY=9d2e4e82-aa7f-428e-b37e-ca50207ccb20
    restart: always
    depends_on:
      - nats
      - postgres

  integration_tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./:/app
    environment:
      - LOG_LEVEL=ERROR
      - SERVER_URL=http://tasks_fastapi:8000
      - ENVIRONMENT=test
      - DB_URL=postgresql+asyncpg://user:password@postgres:5432/tasks
      - CACHE_TTL=5
      - KEYCLOAK_CLIENT_ID=tasks
      - KEYCLOAK_CLIENT_SECRET_KEY=9d2e4e82-aa7f-428e-b37e-ca50207ccb20
    depends_on:
      - tasks_fastapi

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tasks
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user

  nats:
    image: nats:alpine
    restart: always
    ports:
      - 4222:4222
    command:
      - '--jetstream'
