"""empty message

Revision ID: 4a08daeab812
Revises: 34f335cb7bbc
Create Date: 2024-11-12 09:58:21.959719

"""

import os
from typing import Sequence

import sqlalchemy as sa
from alembic import op

env = os.environ.get("ENVIRONMENT", "local")

# revision identifiers, used by Alembic.
revision: str = "4a08daeab812"
down_revision: str | None = "34f335cb7bbc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=None if env == "local" else sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column("task", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column(
        "task_list",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=None if env == "local" else sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column("task_list", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_list", "updated_at")
    op.drop_column("task_list", "created_at")
    op.drop_column("task", "updated_at")
    op.drop_column("task", "created_at")
    # ### end Alembic commands ###
